# authendication credintials
credentials:
  usernames:
    shammi:
      email: shammi@gmail.com
      name: Nusrat Jahan Shammi
      password: 'sham12345' # Placeholder for hashed password of 'abc'

cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - shammi@gmail.com



db:
  host: "localhost"
  user: "root"
  passwd: "C191245shammi"
  database: "expenseDB"
  auth_plugin: "mysql_native_password"

  
email_sender:
  email: "shammi@gmail.com"
  pass: 'sham12345'